# Generated by Django 5.2.12 on 2026-03-28 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('set_name', models.CharField(blank=True, help_text='e.g. Base Set, Topps Chrome', max_length=150)),
                ('edition', models.CharField(blank=True, help_text='e.g. 1st Edition, Unlimited', max_length=100)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('ultra_rare', 'Ultra Rare'), ('secret_rare', 'Secret Rare'), ('promo', 'Promo')], default='common', max_length=20)),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='near_mint', max_length=20)),
                ('language', models.CharField(default='English', max_length=50)),
                ('print_run', models.PositiveIntegerField(blank=True, help_text='Total copies printed', null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, help_text='e.g. Pokémon, Topps, Panini', max_length=100)),
                ('grading_company', models.CharField(choices=[('psa', 'PSA'), ('bgs', 'BGS (Beckett)'), ('cgc', 'CGC'), ('sgc', 'SGC'), ('raw', 'Raw (Ungraded)')], default='raw', max_length=10)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, help_text='Numeric grade, e.g. 9.5', max_digits=4, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('population', models.PositiveIntegerField(blank=True, help_text='Number of copies at this grade', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('auction', 'Auction'), ('offer', 'Open to Offers')], default='fixed', max_length=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_cards', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='catalogue.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
